.\" Copyright (c) 2016 Mark Otaris <mark.otaris@openmailbox.org>
.\" John M Harris, Jr. <johnmh@openblox.org>
.\"
.\" This file is part of OpenBlox.
.\"
.\" OpenBlox is free software: you can redistribute it and/or modify
.\" it under the terms of the GNU Lesser General Public License as published by
.\" the Free Software Foundation, either version 3 of the License, or
.\" (at your option) any later version.
.\"
.\" OpenBlox is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU Lesser General Public License for more details.
.\"
.\" You should have received a copy of the GNU Lesser General Public License
.\" along with OpenBlox.  If not, see <http://www.gnu.org/licenses/>.
.\"
.TH LIBOPENBLOX 3 2016-02-13 "libopenblox" "libopenblox overview"
.SH NAME
libopenblox \- highly configurable core of the OpenBlox game engine.
.SH DESCRIPTION
OpenBlox is aimed towards providing a Lua API similar to that of ROBLOX
to enable developers to create games faster, and with less restrictions.
.SH BUGS
The list of known bugs is available at <https://bugs.openblox.org/>.
This is also where you can report bugs you find while using the library.
.SH AUTHOR
John M. Harris, Jr. (johnmh@openblox.org)
